version: "3.8"

services:
  influxdb:
    image: bitnami/influxdb:1.8.5
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8088:8088"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUXDB_ADMIN_USER_PASSWORD}
      - INFLUXDB_ADMIN_USER_TOKEN=${INFLUXDB_ADMIN_USER_TOKEN}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - INFLUXDB_DB=${INFLUXDB_DB}
    networks:
      - app-tier
    volumes:
      - ./influxdb-data:/var/lib/influxdb

  grafana:
    image: bitnami/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - app-tier
    volumes:
      - ./grafana-data:/var/lib/grafana

networks:
  app-tier:
    driver: bridge

volumes:
  influxdb-data:
  grafana-data:
